[package]
name = "advent-of-code-2019"
version = "0.1.0"
authors = ["Max Davidson <davidsonmax@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.2.0"
itertools = "0.8.2"
bytecount = "0.6.0"
regex = "1.3.1"
lazy_static = "1.4.0"
fancy-regex = "0.3.1"

